#!/usr/bin/python

from sys import argv
from subprocess import Popen, PIPE
from shlex import split
from os.path import dirname, basename
from os import chdir, mkdir

home = '/home/user'

# goto dir in argument
if len(argv) > 1:
	chdir(argv[1])

# which file extensions to search for
file_extensions = ['JPG', 'JPEG', 'GIF', 'PNG', 'TIF', 'TIFF', 'TGA', 'BMP', 'XCF', 'PSD', 'PSP']

# search for pictures in current working directory
files = []
for ext in file_extensions:
	files += Popen(split('find . -iname "*.'+ext+'"'), stdout=PIPE).communicate()[0].strip().split('\n')

# create thumbnails
thumbnail_folder = home+'/.thumbnails'

def thumbname(fname):
	return fname.strip('./').replace('/','-').replace(' ','_').strip('-')

for f in files:
	if f.strip() != '' :
		cmd = 'convert -thumbnail 128x128 "'+f+'" "'+thumbnail_folder+'/'+thumbname(f)+'"'
		print cmd
		Popen(split(cmd), stdout=PIPE).wait()

# extract list of folders
folders = {}
if len(files) > 0:
	sfiles = sorted(files)
	last_folder = ''
	for f in sfiles:
		if f.strip() != '':
			folder = dirname(f)
			if folder != last_folder:
				folders[folder] = []
				last_folder = folder
			folders[folder].append(basename(f))

# write a nice HTML summary
f = open('pictures.html', 'w')
f.write("""<html>

<body>
""")

for folder in sorted(folders.keys()):
	f.write("<b>"+folder+"<br/>\n")
	for img in sorted(folders[folder]):
		#f.write('<img src="'+folder+'/'+img+'" style="max-width:150px; max-height:150px;" />\n')
		f.write('<img src="'+thumbnail_folder+'/'+thumbname(f)+'" style="max-width:150px; max-height:150px;" />\n')
	f.write("<br/>")

f.write("""	</table>
</body>

</html>""")
f.close()
